services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jera
    environment:
      - DB_HOST=localhost
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
